version: '2.1'

services:
  alt-qs-db:
    container_name: alt-qs-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=altqs
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  alt-qs-api:
    container_name: alt-qs-api
    image: alt-qs-api
    build: .
    ports:
      - "8443:8443"
    depends_on:
      alt-qs-db:
        condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://alt-qs-db:5432/altqs
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_OPEN_IN_VIEW=false
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update